update Trailing comma literal
Remove: 
TrailingCommaInLiteral:
  Enabled: false

Add:
TrailingCommaInArrayLiteral:
  Enabled: false
TrailingCommaInHashLiteral:
  Enabled: false

Due to:
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop.yml, please update it)